import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { PGlite } from '@electric-sql/pglite'
import { MORSE, normalize } from '../src/lib/morse.ts'
import { lessons } from '../src/content/lessons.ts'

test('server enforces XP, membership, immutable ordered duels and deadlines', async () => {
  const db = new PGlite()
  await db.exec(`create schema auth; create role authenticated; create role anon;
    create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated;`)
  const migration = await readFile(new URL('../supabase/migrations/202609130001_morse.sql', import.meta.url), 'utf8')
  await db.exec(migration)
  await db.exec(`insert into auth.users values ('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002'),('00000000-0000-0000-0000-000000000003');
    insert into public.lesson_catalog values ('test',0,'Letras','A B','1');`)
  const login = async (n: number) => db.exec(`reset role; set request.jwt.claim.sub='00000000-0000-0000-0000-${String(n).padStart(12,'0')}'; set role authenticated;`)
  const rpc = async (sql: string) => (await db.query<{ value: any }>(`select ${sql} as value`)).rows[0]!.value
  await db.exec(`set request.jwt.claim.sub=''; set role authenticated;`)
  await assert.rejects(rpc(`create_duel('send','Letras',60,'visual')`), /Inicia sesión/)
  await assert.rejects(rpc(`submit_practice('test',0,'receive','A B','00000000-0000-0000-0000-000000000099')`), /Inicia sesión/)
  await login(1)
  await db.exec('reset role')
  assert.equal(await rpc(`morse_normalize('¿Árbol, niño?')`), 'ARBOL, NIÑO?')
  assert.equal(await rpc(`morse_decode('.- / -...')`), 'A B')
  assert.equal(await rpc(`morse_normalize('niño ágil')`), 'NIÑO AGIL')
  assert.equal(await rpc(`morse_decode('.-/-...')`), 'A B')
  assert.equal(await rpc(`morse_decode(E'\\t.- \\n/ -...\\t')`), 'A B')
  await assert.rejects(rpc(`morse_normalize('ß')`), /no admitidos/)
  await assert.rejects(rpc(`morse_decode('/ .-')`), /separación/)
  assert.equal(await rpc(`morse_distance('ABC','AXBC')`), 1)
  await db.exec('set role authenticated')
  await assert.rejects(rpc(`morse_distance('ABC','AXBC')`), /permission denied/)
  await assert.rejects(rpc(`submit_practice('test',0,'receive','A B','00000000-0000-0000-0000-000000000010')`).then(async first => {
    assert.equal(first.xp, 10)
    assert.equal((await rpc(`submit_practice('test',0,'receive','WRONG','00000000-0000-0000-0000-000000000010')`)).xp, 10)
    return db.exec('update profiles set xp=9999')
  }), /permission denied/)
  const room = await rpc(`create_duel('send','Letras',60,'visual')`)
  await login(3)
  await assert.rejects(rpc(`duel_state('${room.id}')`), /No perteneces/)
  assert.equal((await db.query(`select * from rooms`)).rows.length, 0)
  await login(2)
  await rpc(`join_duel('${room.code}')`)
  await rpc(`ready_duel('${room.id}')`)
  await login(1)
  await rpc(`ready_duel('${room.id}')`)
  await assert.rejects(rpc(`submit_segment('${room.id}',0,'.-')`), /no está activo/)
  await db.exec(`reset role; update rooms set starts_at=now()-interval '4 seconds', ends_at=now()+interval '60 seconds' where id='${room.id}'; set role authenticated;`)
  await assert.rejects(rpc(`submit_segment('${room.id}',1,'-...')`), /orden/)
  await rpc(`submit_segment('${room.id}',0,'.-')`)
  await assert.rejects(rpc(`submit_segment('${room.id}',0,'.-')`), /orden/)
  await rpc(`submit_segment('${room.id}',1,'-...')`)
  await login(2)
  await rpc(`submit_segment('${room.id}',0,'-')`)
  await db.exec(`reset role; update rooms set ends_at=now()-interval '1 second' where id='${room.id}'; set role authenticated;`)
  await assert.rejects(rpc(`submit_segment('${room.id}',1,'-...')`), /no está activo/)
  await login(1)
  const final = await rpc(`finish_duel('${room.id}',true)`)
  assert.equal(final.status, 'finished')
  assert.equal(final.winner_id, '00000000-0000-0000-0000-000000000001', 'a late forfeit cannot change the result at the deadline')
  await login(1)
  assert.equal((await rpc(`duel_state('${room.id}')`)).winner_id, final.winner_id)
  assert.equal((await db.query<{xp:number}>(`select xp from profiles where id=auth.uid()`)).rows[0]!.xp, 30)
  await assert.rejects(db.exec(`select * from room_challenges`), /permission denied/)
  await assert.rejects(rpc(`award_xp(auth.uid(),'forged',999)`), /permission denied/)
  await assert.rejects(rpc(`close_duel('${room.id}')`), /permission denied/)
  await db.exec(`reset role; update profiles set last_attempt=null; set role authenticated;`)
  const completed = await rpc(`submit_practice('test',0,'send','.- / -...','00000000-0000-0000-0000-000000000011')`)
  assert.equal(completed.xp, 65, '10 for the exercise plus a one-time 25 lesson bonus')
  await db.exec(`reset role; update profiles set last_attempt=null; set role authenticated;`)
  assert.equal((await rpc(`submit_practice('test',0,'send','.- / -...','00000000-0000-0000-0000-000000000012')`)).xp, 75)
  await assert.rejects(rpc(`submit_practice('test',0,'send','.- / -...','00000000-0000-0000-0000-000000000013')`), /dos segundos/)
  const reception = await rpc(`create_duel('receive','Letras',60,'audio')`)
  await assert.rejects(rpc(`finish_duel('${reception.id}',null)`), /Decisión no válida/)
  await login(2)
  await rpc(`join_duel('${reception.code}')`)
  await rpc(`ready_duel('${reception.id}')`)
  await login(3)
  await assert.rejects(rpc(`join_duel('${reception.code}')`), /llena/)
  await login(1)
  await rpc(`ready_duel('${reception.id}')`)
  await db.exec(`reset role; update rooms set starts_at=now()-interval '4 seconds' where id='${reception.id}'; set role authenticated;`)
  assert.deepEqual((await rpc(`duel_state('${reception.id}')`)).segments, ['.-','-...'])
  await rpc(`submit_segment('${reception.id}',0,'A')`)
  assert.equal((await rpc(`finish_duel('${reception.id}',true)`)).winner_id, '00000000-0000-0000-0000-000000000002')
  assert.equal((await db.query<{xp:number}>(`select xp from profiles where id=auth.uid()`)).rows[0]!.xp, 75, 'forfeit never awards XP')
  await login(2)
  assert.equal((await db.query<{xp:number}>(`select xp from profiles where id=auth.uid()`)).rows[0]!.xp, 0, 'winning without an effective submission awards nothing')
  const expired = await rpc(`create_duel('receive','Letras',60,'visual')`)
  await db.exec(`reset role; update rooms set expires_at=now()-interval '1 second' where id='${expired.id}';`)
  await login(3)
  await assert.rejects(rpc(`join_duel('${expired.code}')`), /caducada/)
  await login(2)
  await assert.rejects(rpc(`ready_duel('${expired.id}')`), /no disponible/)
  const lateReception = await rpc(`create_duel('receive','Letras',60,'visual')`)
  await rpc(`ready_duel('${lateReception.id}')`)
  await login(1)
  await rpc(`join_duel('${lateReception.code}')`)
  await rpc(`ready_duel('${lateReception.id}')`)
  await db.exec(`reset role; update rooms set starts_at=now()-interval '70 seconds',ends_at=now()-interval '10 seconds' where id='${lateReception.id}'; set role authenticated;`)
  await assert.rejects(rpc(`submit_segment('${lateReception.id}',0,'A')`), /no está activo/)
  assert.equal((await rpc(`duel_state('${lateReception.id}')`)).winner_id, null)
  await db.exec('reset role')
  await db.exec(await readFile(new URL('../supabase/seed.sql', import.meta.url), 'utf8'))
  for (const [symbol, morse] of Object.entries(MORSE)) {
    assert.equal((await db.query<{ value: string }>('select morse_encode($1) as value', [symbol])).rows[0]!.value, morse)
    assert.equal((await db.query<{ value: string }>('select morse_decode($1) as value', [morse])).rows[0]!.value, symbol)
  }
  const catalog = (await db.query<{lesson_id:string;exercise_index:number;target:string}>(`select * from lesson_catalog where lesson_id<>'test'`)).rows
  assert.equal(catalog.length, lessons.reduce((sum, lesson) => sum + lesson.exercises.length, 0))
  for (const row of catalog) assert.equal(row.target, normalize(lessons.find(lesson => lesson.id === row.lesson_id)!.exercises[row.exercise_index]!))
  await db.close()
})
